# Generated by Django 5.2.9 on 2025-12-19 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reference_date",
                    models.CharField(
                        db_index=True, help_text="YYYY-MM 형식 (예: 2024-05)", max_length=7, verbose_name="기준 년월"
                    ),
                ),
                ("department", models.CharField(blank=True, default="", max_length=100, verbose_name="부서명")),
                ("department_code", models.CharField(blank=True, default="", max_length=20, verbose_name="부서코드")),
                ("revenue", models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="매출액")),
                ("budget", models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="예산")),
                ("expenditure", models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="지출액")),
                ("paper_count", models.IntegerField(default=0, verbose_name="논문수")),
                ("patent_count", models.IntegerField(default=0, verbose_name="특허수")),
                ("project_count", models.IntegerField(default=0, verbose_name="프로젝트수")),
                (
                    "extra_metric_1",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="추가지표1"),
                ),
                (
                    "extra_metric_2",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="추가지표2"),
                ),
                ("extra_text", models.TextField(blank=True, default="", verbose_name="비고")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
            ],
            options={
                "verbose_name": "실적 데이터",
                "verbose_name_plural": "실적 데이터",
                "ordering": ["-reference_date", "department"],
                "indexes": [
                    models.Index(fields=["reference_date"], name="api_perform_referen_fd436f_idx"),
                    models.Index(fields=["department"], name="api_perform_departm_83663d_idx"),
                    models.Index(fields=["reference_date", "department"], name="api_perform_referen_bc44e3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentRoster",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("student_id", models.CharField(max_length=20, unique=True, verbose_name="학번")),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("college", models.CharField(blank=True, default="", max_length=100, verbose_name="단과대학")),
                ("department", models.CharField(blank=True, default="", max_length=100, verbose_name="학과")),
                ("grade", models.IntegerField(default=0, verbose_name="학년")),
                (
                    "program_type",
                    models.CharField(
                        choices=[("학사", "학사"), ("석사", "석사"), ("박사", "박사")],
                        default="학사",
                        max_length=20,
                        verbose_name="과정구분",
                    ),
                ),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[("재학", "재학"), ("휴학", "휴학"), ("졸업", "졸업"), ("제적", "제적")],
                        default="재학",
                        max_length=20,
                        verbose_name="학적상태",
                    ),
                ),
                ("gender", models.CharField(blank=True, default="", max_length=10, verbose_name="성별")),
                ("admission_year", models.IntegerField(blank=True, null=True, verbose_name="입학년도")),
                ("advisor", models.CharField(blank=True, default="", max_length=100, verbose_name="지도교수")),
                ("email", models.EmailField(blank=True, default="", max_length=254, verbose_name="이메일")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
            ],
            options={
                "verbose_name": "학생 명단",
                "verbose_name_plural": "학생 명단",
                "ordering": ["student_id"],
                "indexes": [
                    models.Index(fields=["department"], name="api_student_departm_829d5a_idx"),
                    models.Index(fields=["enrollment_status"], name="api_student_enrollm_a4aa3a_idx"),
                    models.Index(fields=["program_type"], name="api_student_program_488e62_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UploadLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference_date", models.CharField(max_length=7, verbose_name="기준 년월")),
                ("filename", models.CharField(max_length=255, verbose_name="파일명")),
                ("row_count", models.IntegerField(default=0, verbose_name="처리 행 수")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "성공"), ("failed", "실패")],
                        default="success",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="", verbose_name="에러 메시지")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="업로드 일시")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로드 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "업로드 이력",
                "verbose_name_plural": "업로드 이력",
                "ordering": ["-created_at"],
            },
        ),
    ]
