name: Test Suite (Backend + Frontend)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Backend Tests with Coverage
        run: |
          pytest api/tests/test_excel_parser.py -v --cov=api --cov-report=xml --cov-report=term-missing
        continue-on-error: false

      - name: Upload Backend Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-coverage-report
          path: backend/coverage.xml
          retention-days: 7

      - name: Upload Backend Coverage to Codecov
        uses: codecov/codecov-action@v3
        if: always()
        with:
          files: ./backend/coverage.xml
          flags: backend
          name: backend-coverage
          fail_ci_if_error: false

      - name: Backend Test Summary
        if: always()
        run: |
          echo "### Backend Test Results" >> $GITHUB_STEP_SUMMARY
          echo "- Python Version: 3.13" >> $GITHUB_STEP_SUMMARY
          echo "- Test Command: pytest api/tests/test_excel_parser.py -v --cov=api" >> $GITHUB_STEP_SUMMARY
          echo "- Coverage Report: Generated at coverage.xml" >> $GITHUB_STEP_SUMMARY

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run Frontend Tests with Coverage
        run: |
          npm test -- --coverage --watchAll=false
        continue-on-error: false

      - name: Upload Frontend Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: frontend-coverage-report
          path: frontend/coverage/
          retention-days: 7

      - name: Upload Frontend Coverage to Codecov
        uses: codecov/codecov-action@v3
        if: always()
        with:
          files: ./frontend/coverage/coverage-final.json
          flags: frontend
          name: frontend-coverage
          fail_ci_if_error: false

      - name: Frontend Test Summary
        if: always()
        run: |
          echo "### Frontend Test Results" >> $GITHUB_STEP_SUMMARY
          echo "- Node.js Version: 20" >> $GITHUB_STEP_SUMMARY
          echo "- Test Command: npm test -- --coverage --watchAll=false" >> $GITHUB_STEP_SUMMARY
          echo "- Coverage Report: Generated at coverage/" >> $GITHUB_STEP_SUMMARY

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]
    if: always()

    steps:
      - name: Check Test Results
        run: |
          echo "### Overall Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Backend Tests: ${{ needs.backend-test.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Frontend Tests: ${{ needs.frontend-test.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.backend-test.result }}" == "failure" ] || [ "${{ needs.frontend-test.result }}" == "failure" ]; then
            echo "**Status: FAILED**" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "**Status: PASSED**" >> $GITHUB_STEP_SUMMARY
          fi
